## Random mudule:
Python defines a set of functions that are used to generate or manipulate random numbers. This article covers:

- the random module
- reproduce numbers with random.seed()
- create cryptographically strong random numbers with the secrets module
- create random nd arrays with numpy.random

### Pseudo-random number:
This module implements pseudo-random number generators for various distributions. It uses the Mersenne Twister algorithm. It is called pseudo-random, because the numbers seem random, but are reproducable.

In [1]:
import random

In [6]:
a = random.random() # random float in [0,1)
a

0.5794475055480983

In [7]:
a = random.uniform(1, 10) # random float in range [a,b]
a

5.107100587765435

In [15]:
a = random.randint(1, 10)
# random integer in range [a,b]. b is included
a

10

In [12]:
a = random.randrange(1, 10)
# random integer in range [a,b). b is excluded
a

1

In [18]:
a = random.normalvariate(0, 1)
# random float from a normal distribution with mu= mean and sigma=std
a

0.5174490508443539

In [33]:
mylist = list("ABCDEFGH")
print(mylist)

# pics a random element
a = random.choice(mylist)
print(a)

# pics unique elements randomly
a = random.sample(mylist, 3)
print(a)

# to pics elements randomly with repetations
a = random.choices(mylist, k=3)
print(a)

# to shuffle a list-but changes the original list
random.shuffle(mylist)
print(mylist)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
G
['B', 'H', 'D']
['F', 'B', 'G']
['C', 'H', 'A', 'B', 'E', 'F', 'G', 'D']


### The seed generator:

With random.seed(), you can make results reproducible, and the chain of calls after random.seed() will produce the same trail of data. The sequence of random numbers becomes deterministic, or completely determined by the seed valus

In [36]:
random.seed(1)

print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2


In [37]:
# changing seed value changes the numbers
random.seed(5)

print(random.random())
print(random.randint(1, 10))

0.6229016948897019
6


### The secrets module:

The secrets module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.
In particularly, secrets should be used in preference to the default pseudo-random number generator in the random module, which is designed for modelling and simulation, not security or cryptography.

Disadvantage is that it takes more time.

In [38]:
import secrets

In [40]:
# random integer in range [0, n).
a = secrets.randbelow(10)
a

0

In [42]:
# return an integer with k random bits.
a = secrets.randbits(4) # i.e in the form of binary digits 0 and 1's
a

9

In [45]:
# choose a random element from a sequence
a  = secrets.choice(mylist)
a

'B'

### Random numbers with NumPy

Create random numbers for nd arrays. The NumPy pseudorandom number generator is different from the Python standard library pseudorandom number generator.
Importantly, seeding the Python pseudorandom number generator does not impact the NumPy pseudorandom number generator. It must be seeded and used separately.

In [47]:
import numpy as np

In [48]:
a = np.random.rand(3)
a

array([0.63877813, 0.81556039, 0.65928539])

In [49]:
a = np.random.rand(3, 1)
a

array([[0.23569839],
       [0.72461848],
       [0.24552273]])

In [53]:
a = np.random.randint(5, 8, 4) # lower limit, higher limit, size
a

array([6, 5, 6, 6])

In [55]:
a = np.random.randint(5, 8, (4, 7)) # lower limit, higher limit, size
a

array([[6, 5, 6, 6, 7, 5, 5],
       [5, 7, 7, 5, 5, 5, 5],
       [6, 5, 7, 6, 7, 6, 5],
       [5, 5, 7, 7, 5, 6, 6]])

In [56]:
a = np.random.randint(5, 8, (4, 3))
print(a)
np.random.shuffle(a) # changes only in one axis along rows
print(a)

[[6 7 5]
 [7 5 5]
 [6 7 5]
 [5 6 5]]
[[7 5 5]
 [5 6 5]
 [6 7 5]
 [6 7 5]]


In [59]:
# numpy as seperate seed option
# but .seed func. from random module doesn't work here
np.random.seed(1) 
a = np.random.randint(5, 8, (4, 3))
print(a)

[[6 5 5]
 [6 6 5]
 [5 6 5]
 [6 5 7]]
